# Generated by Django 3.1.3 on 2020-11-28 09:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfectingVirus',
            fields=[
                ('virus_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('common_name', models.CharField(max_length=200)),
                ('max_infectious_period', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('chp_staff_number', models.CharField(max_length=7)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('date_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_to', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('R', 'Residence'), ('W', 'Workplace'), ('V', 'Visit')], default='R', max_length=30)),
                ('grid_coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.coordinate')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmedCase',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('Local', 'Local'), ('Imported', 'Imported')], default='Local', max_length=20)),
                ('location', models.ManyToManyField(to='application.Location')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.patient')),
                ('virus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.infectingvirus')),
            ],
        ),
    ]
